#端口
server:
  port: 8072
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

spring:
  application:
    name: jieancai-index
  profiles:
    active: dev
  #  数据库连接
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.200.206:3306/tender?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
          username: develop
          password: dev@2020
          type: com.zaxxer.hikari.HikariDataSource
          hikari:
            connection-timeout: 5000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
            min-idle: 5                 # 最小连接数
            max-pool-size: 20           # 最大连接数
            auto-commit: true               # 自动提交
            idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
            max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
            connection-test-query: SELECT 1